// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_dynamodb_all_tables_region": "us-west-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "foodTable-dev",
            "region": "us-west-2"
        }
    ],
    "aws_cognito_identity_pool_id": "us-west-2:ac7ec996-e1e5-47d5-8843-083a904ce01e",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_NIDBwzzVx",
    "aws_user_pools_web_client_id": "6fo1k2ktoomqf5b2d5i1k8mrem",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "foodapi",
            "endpoint": "https://430aio1ql3.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ],
    "aws_content_delivery_bucket": "myapp2-20191007140352-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "https://d2oa9pglcranyv.cloudfront.net"
};


export default awsmobile;
